export const LOGIN         = '/cinema-svc/auth/login';   // ip addr are based on docker-compose
export const SIGN_UP       = '/cinema-svc/auth/signup';
export const LOGOUT        = '/cinema-svc/auth/logout';
export const PROTECTED     = '/cinema-svc/auth/protected';
export const AUTH          = '/cinema-svc/auth';
export const DETAILS       = "/cinema-svc/details";
export const PERMISSIONS   = "/cinema-svc/permissions";
export const MEMBERS       = "/cinema-svc/members";
export const MOVIES        = "/cinema-svc/movies";
export const SUBSCRIPTIONS = "/cinema-svc/subscriptions";